service: guria-aws-js-practitioner
frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate
  - log-output-values

custom:
  vars:
    bucketName: ${self:service}-${sls:stage}
  log-output-values:
    - template: "Web App deployed to: https://{WebAppDistributionOutput}"
  s3Sync:
    - bucketName: ${self:custom.vars.bucketName}
      localDir: dist
      deleteRemoved: true
      cacheControl: "max-age=31536000, no-transform, public"
      defaultContentType: "text/html"
  cloudfrontInvalidate:
    - distributionIdKey: "WebAppDistributionIdOutput"
      autoInvalidate: true
      items:
        - "/index.html"

resources:
  Resources:
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.vars.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: "AllowCloudFrontAccessIdentity"
              Effect: Allow
              Action: s3:GetObject
              Resource: !Sub ${WebAppS3Bucket.Arn}/*
              Principal:
                AWS:
                  Fn::Join:
                    - " "
                    - - "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity"
                      - !Ref OriginAccessIdentity

    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: Access identity between CloudFront and S3 bucket

    WebAppDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt WebAppS3Bucket.RegionalDomainName
              Id: myS3Origin
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OriginAccessIdentity}
          Enabled: true
          IPV6Enabled: true
          HttpVersion: http2
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods: ["GET", "HEAD", "OPTIONS"]
            CachedMethods: ["GET", "HEAD", "OPTIONS"]
            ForwardedValues:
              Headers:
                - Access-Control-Request-Headers
                - Access-Control-Request-Method
                - Origin
                - Authorization
              QueryString: false
              Cookies:
                Forward: none
            TargetOriginId: myS3Origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            DefaultTTL: 0
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    WebAppS3BucketOutput:
      Value: !Ref WebAppS3Bucket
    WebAppDistributionOutput:
      Value: !GetAtt WebAppDistribution.DomainName
    WebAppDistributionIdOutput:
      Value:
        Ref: WebAppDistribution
