services:
  api-gateway:
    path: ./services/api-gateway
    params:
      ResourcePrefix: ajp-${sls:stage}

  fe-distribution:
    path: ./services/fe-distribution
    params:
      ResourcePrefix: ajp-${sls:stage}

  fixtures:
    path: ./services/fixtures
    params:
      ResourcePrefix: ajp-${sls:stage}
      WebAppDistributionDomain: ${fe-distribution.WebAppDistributionDomain}
      WebAppCustomDomain: ${fe-distribution.WebAppCustomDomain}

  products-api:
    path: ./services/products-api
    params:
      ResourcePrefix: ajp-${sls:stage}
      FixturesS3BucketName: ${fixtures.FixturesS3BucketName}
      ApiGatewayRestApiId: ${api-gateway.ApiGatewayRestApiId}
      ApiGatewayRestApiRootResourceId: ${api-gateway.ApiGatewayRestApiRootResourceId}
      WebAppDistributionDomain: ${fe-distribution.WebAppDistributionDomain}
      WebAppCustomDomain: ${fe-distribution.WebAppCustomDomain}
      HostedZoneDomain: ${fe-distribution.HostedZoneDomain}

  products-import:
    path: ./services/products-import
    params:
      ResourcePrefix: ajp-${sls:stage}
      FixturesS3BucketName: ${fixtures.FixturesS3BucketName}
      ApiGatewayRestApiId: ${api-gateway.ApiGatewayRestApiId}
      ApiGatewayRestApiRootResourceId: ${api-gateway.ApiGatewayRestApiRootResourceId}
      WebAppDistributionDomain: ${fe-distribution.WebAppDistributionDomain}
      WebAppCustomDomain: ${fe-distribution.WebAppCustomDomain}
      ImportedProductsQueue: ${products-api.ImportedProductsQueue}
      ImportedProductsQueueUrl: ${products-api.ImportedProductsQueueUrl}

  shop-frontend-app:
    path: ./services/shop-frontend-app
    dependsOn:
      - api-gateway
      - fe-distribution
      - products-api
      - products-import
    params:
      ApiGatewayRestApiId: ${api-gateway.ApiGatewayRestApiId}
      ProductsApiServiceEndpoint: ${api-gateway.ApiGatewayRestApiEndpoint}
      WebAppS3BucketName: ${fe-distribution.WebAppS3BucketName}
      WebAppDistributionId: ${fe-distribution.WebAppDistributionId}
      WebAppDistributionDomain: ${fe-distribution.WebAppDistributionDomain}
      WebAppCustomDomain: ${fe-distribution.WebAppCustomDomain}
