service: ajp-api-gateway

provider:
  name: aws
  runtime: nodejs16.x

resources:
  Resources:
    ApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${param:ResourcePrefix}-rest
        Description: API Gateway for the AWS JS Practitioner course

  Outputs:
    ApiGatewayRestApiId:
      Value: !Ref ApiGW

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt: [ApiGW, RootResourceId]

    ApiGatewayRestApiEndpoint:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGW
            - ".execute-api.${aws:region}.amazonaws.com/${sls:stage}"
