Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      ImportSourceSpecification:
        InputCompressionType: "NONE"
        InputFormat: "DYNAMODB_JSON"
        S3BucketSource:
          S3Bucket: "${param:FixturesS3BucketName}"
          S3KeyPrefix: "seed/products.ndjson"

  ProductStocksTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      ImportSourceSpecification:
        InputCompressionType: "NONE"
        InputFormat: "DYNAMODB_JSON"
        S3BucketSource:
          S3Bucket: "${param:FixturesS3BucketName}"
          S3KeyPrefix: "seed/product-stocks.ndjson"

  ImportedProductsQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${param:ResourcePrefix}-imported-products"
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ImportedProductsDeadLetterQueue.Arn
        maxReceiveCount: 3

  ImportedProductsDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "${param:ResourcePrefix}-imported-products-dlq"
      MessageRetentionPeriod: 1209600
