service: ajp-shop-frontend
frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate
  - "@guria.dev/serverless-scriptable"
  - "@guria.dev/serverless-log-output-values"

custom:
  log-output-values:
    - template: |
        Web App deployed to Cloudfront and available at following addresses:
        * https://${param:WebAppDistributionDomain}
        * https://${param:WebAppCustomDomain}
        Swagger Schema available at:
        * https://${param:WebAppCustomDomain}/swagger/swagger.json
        Swagger UI available at:
        * https://${param:WebAppCustomDomain}/swagger/index.html
  s3Sync:
    - bucketName: ${param:WebAppS3BucketName}
      localDir: dist
      deleteRemoved: true
  cloudfrontInvalidate:
    - distributionId: ${param:WebAppDistributionId}
      autoInvalidate: true
      items:
        - "/index.html"
        - "/config.js"
        - "/swagger.json"
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: |
        echo "_CONFIG_ = {BASE_URL: \"${param:ProductsApiServiceEndpoint}\"}" > public/config.js
        npm run build
        SWAGGER_DIST_PATH=$(node -e 'console.log(require("swagger-ui-dist").getAbsoluteFSPath())')
        cp -r $SWAGGER_DIST_PATH/ dist/swagger
        sed -i 's/url: ".*"/url: "swagger.json"/g' dist/swagger/swagger-initializer.js
        aws apigateway get-export --parameters extensions='apigateway' --rest-api-id ${param:ApiGatewayRestApiId} --stage-name ${sls:stage} --export-type swagger dist/swagger/swagger.json
